In [1]:
from scipy.sparse import csr_matrix
from scipy import sparse
import numpy as np

In [2]:
# 1. creat Compressed Sparse Row matrix (csr)
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html

# create element = 0, shape = (3, 4), dtype=np.int8 csr matrix
sp_1 = csr_matrix((3, 4), dtype=np.int8)

# create 
# element = [1,2,3,4,5,6]
# position = [(0,0), (0,2), (1,2), (2,0), (2,1), (2,2)]
# dtype default = np.int64
# csr matrix
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
sp_2 = csr_matrix((data, (row, col)), shape=(3, 3))

# create 
# data = [1,2,3,4,5,6]
# column indices = [0,2,2,0,1,2]
# index pointer = [0,2,3,6] 
indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
sp_3 = csr_matrix((data, indices, indptr), shape=(3, 3))

sp_1, sp_1.toarray(), sp_2, sp_2.toarray(), sp_3, sp_3.toarray()

(<3x4 sparse matrix of type '<class 'numpy.int8'>'
 	with 0 stored elements in Compressed Sparse Row format>,
 array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=int8),
 <3x3 sparse matrix of type '<class 'numpy.int64'>'
 	with 6 stored elements in Compressed Sparse Row format>,
 array([[1, 0, 2],
        [0, 0, 3],
        [4, 5, 6]]),
 <3x3 sparse matrix of type '<class 'numpy.int64'>'
 	with 6 stored elements in Compressed Sparse Row format>,
 array([[1, 0, 2],
        [0, 0, 3],
        [4, 5, 6]]))

In [3]:
# 1.5 the method and attributes
print(dir(sp_1))

['__abs__', '__add__', '__array_priority__', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__idiv__', '__imul__', '__init__', '__init_subclass__', '__isub__', '__iter__', '__itruediv__', '__le__', '__len__', '__lt__', '__matmul__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__pow__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__rmatmul__', '__rmul__', '__round__', '__rsub__', '__rtruediv__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '_add_dense', '_add_sparse', '_arg_min_or_max', '_arg_min_or_max_axis', '_asindices', '_binopt', '_cs_matrix__get_has_canonical_format', '_cs_matrix__get_sorted', '_cs_matrix__set_has_canonical_format', '_cs_matrix__set_sorted', '_deduped_data', '_divide', '_divide_sparse', '

**2 what ia index pointer?**

[ref](https://stackoverflow.com/questions/52299420/scipy-csr-matrix-understand-indptr)

**what is it?**

1. If the sparse matrix has $M$ rows, `indptr` is an array contains $M+1$ elements
2. for row **i**, `[ indptr[i]:indptr[i+1] ]` returns the indices of element take from `data` and `indices` corresponding to row **i**

<img src='./assets/scipy_1.png'></img>

e.g. 

`data = [a,b,c,d,e,f,g,h,i,j,k]`, `n_elements = 11` 

`indices(columns) = [5,1,6,3,3,4,5,0,5,3,5]`, `n_elements = 11`

`indptr = [0,1,3,4,7,8,9,11]`, `n_elements = 8` -> means there is 7 rows(row0 ~ row6)

all right, how to fill the values?

1. `index[0:1]` row 0 filling data **a** at indices(columns) **5**
2. `index[1:3]` row 1 filling data **b, c** at indices(columns) **1, 6**
3. `index[3:4]` row 2 filling data **d** at indices(columns) **3**
4. `index[4:7]` row 3 filling data **e, f, g** at indices(columns) **3, 4, 5**
5. `index[7:8]` row 4 filling data **h** at indices(columns) **0**
6. `index[8:9]` row 5 filling data **i** at indices(columns) **5**
7. `index[9:11]` row 6 filling data **j, k** at indices(columns) **3, 5**

Note : the values `indptr` are necessarily increasing and unique

**why use this?**

you can observse that the index stored size is more smaller than

`data, row, column` approach. 

use it when you need it.



In [4]:
# 3 
# sampling the csr matrix by row
# Consider csr matrix with shape (User, Items) = (10, 20)
# Random Sampling 3 users, return a csr matrix format

# https://stackoverflow.com/questions/13843352/what-is-the-fastest-way-to-slice-a-scipy-sparse-matrix
########## Consider efficient slicing row index of csr
# Advantages of the CSR format
# efficient arithmetic operations CSR + CSR, CSR * CSR, etc.

# efficient row slicing

# fast matrix vector products
########## Begin
# element = [1, 1, 1, 1, 1, 1] - have interacted items
# position = [(0,0), (0,2), (1,2), (2,0), (2,1), (2,2)]
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 1, 1, 1, 1, 1])
A = csr_matrix((data, (row, col)), shape=(10, 20))

n_sampled_users = 3
n_total_users = A.shape[0]
rdn_user_idx = np.random.choice(np.arange(n_total_users),
                                size=n_sampled_users,replace=False) # without replacement
print(rdn_user_idx)
A[rdn_user_idx, :]

[1 5 9]


<3x20 sparse matrix of type '<class 'numpy.int64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [5]:
# 4 
# the attributes indptr and indices
# element = [1, 1, 1, 1, 1, 1] - have interacted items
# position = [(0,0), (0,2), (1,2), (2,0), (2,1), (2,2)]
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 1, 1, 1, 1, 1])
A = csr_matrix((data, (row, col)), shape=(3,3))
display(A.todense())


for user in range(A.shape[0]):
        start_usr = A.indptr[user]
        end_usr = A.indptr[user + 1]
        print(A.indices[start_usr:end_usr]) # this will show the non zero column per user

matrix([[1, 0, 1],
        [0, 0, 1],
        [1, 1, 1]])

[0 2]
[2]
[0 1 2]


In [7]:
%%timeit
# 5. Knowing the pros and cons of different sparse matrix
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html
# CSR
#   Pros: efficient arithmetic operations, efficient row slicing, fast matrix vector products
#   Cons: slow column sclining operations(Consider CSC), changes to the sparsity structure are expensive(Consider LIL or DOK)

M = sparse.random(5, 10, .2, format='csr')
# column operation
M[-1, :] = np.arange(10)

/Users/YuLong/miniconda3/envs/py_37_ds/lib/python3.7/site-packages/scipy/sparse/_index.py:124: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)


512 µs ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%%timeit
M = sparse.random(5,10,.2,format='csr')
M1=M.tolil(); M1[-1,:] = np.arange(10); M = M1.tocsr()


419 µs ± 8.36 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
%%timeit
M = sparse.random(5,10,.2,format='lil')
M[-1,:] = np.arange(10)
M = M.tocsr()

414 µs ± 2.32 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
