## There are alternative solution and hits: 
### more readable
 > 26, 27, 38, 48
### more effient (vectorlized)
 > 40
 ### when to use it?
 > 9, 15, 16, 44, 45, 46
 ### hints
 > 5, 7, 20, 21, 24, 30, 40, 42, 43, 45

In [1]:
import numpy as np
np.random.seed(seed=42)

In [2]:
# 1. Import numpy as np and see the version
# Difficulty Level: L1

# Q. Import numpy as `np` and print the version number.

np.__version__

'1.16.2'

In [3]:
# 2. How to create a 1D array?
# Difficulty Level: L1

# Q. Create a 1D array of numbers from 0 to 9

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 3. How to create a boolean array?
# Difficulty Level: L1

# Q. Create a 3×3 numpy array of all True’s

np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
# 4. How to extract items that satisfy a given condition from 1D array?
# Difficulty Level: L1

# Q. Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

condintion = arr % 2 == 1
arr[condintion]

array([1, 3, 5, 7, 9])

In [6]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
# Difficulty Level: L1

# Q. Replace all odd numbers in arr with -1

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.where(arr % 2 == 1, -1, arr)

# Hint
# 4,5題比較，如果只想要部分符合條件的結果 - 用 boolean array
# 如果想要整個array的結果, 符合與不符合分別map到不同的值 - 用 np.where
# When to use
# Feature engineering, 根據條件來變更array的值, 非常常用

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
# 6. How to replace items that satisfy a condition without affecting the original array?
# Difficulty Level: L2
# Q. Replace all odd numbers in arr with -1 without changing arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

result = np.where(arr % 2 == 1, -1, arr)
print(arr, result, sep='\n')

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
# 7. How to reshape an array?
# Difficulty Level: L1

# Q. Convert a 1D array to a 2D array with 2 rows

arr = np.arange(10)

arr.reshape(2, -1)

# hint 
# -1 表示剩餘的行/列可以被決定 在此例中，我們已經決定rows = 2
# 則 columns 為 10 / 2 = 5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# 8. How to stack two arrays vertically?
# Difficulty Level: L2

# Q. Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
# 9. How to stack two arrays horizontally?
# Difficulty Level: L2

# Q. Stack the arrays a and b horizontally.

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a, b])

# when to use?
# 在迴圈中，例如Cross-validation, 做陣列操作, 例如合併特徵重要度,
# 或是拼接特徵

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [11]:
# 10. How to generate custom sequences in numpy without hardcoding?
# Difficulty Level: L2

# Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

a = np.array([1,2,3])

result = np.hstack([np.repeat(a, 3),
                    np.tile(a, 2)])
result

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3])

In [12]:
# 11. How to get the common items between two python numpy arrays?
# Difficulty Level: L2

# Q. Get the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

In [13]:
# 12. How to remove from one array those items that exist in another?
# Difficulty Level: L2

# Q. From array a remove all items present in array b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

intersect = np.intersect1d(a, b)
b[~np.isin(b, a)]

array([ 7, 10,  7,  9,  9,  8])

In [14]:
# 13. How to get the positions where elements of two arrays match?
# Difficulty Level: L2
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.argwhere(a==b).reshape(-1)

array([1, 3, 5, 7], dtype=int64)

In [15]:
# 14. How to extract all numbers between a given range from a numpy array?
# Difficulty Level: L2
a = np.array([2, 6, 1, 9, 10, 3, 27])

idx = np.argwhere((5 <= a) & (a<=10)).reshape(-1)
a[idx]

array([ 6,  9, 10])

In [16]:
# 15. How to make a python function that handles scalars to work on numpy arrays?
# Difficulty Level: L2
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
v_maxx = np.vectorize(maxx, otypes=[int])

# when to use
# you want faster speed but no np function suit your case
# then define it, vectorlize it
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
v_maxx(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [17]:
# 16. How to swap two columns in a 2d numpy array?
# Difficulty Level: L2
arr = np.arange(9).reshape(3,3)
# when to use
# change your feature values if they are numpy.array
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [18]:
# 17. How to swap two rows in a 2d numpy array?
# Difficulty Level: L2
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [19]:
# 18. How to reverse the rows of a 2D array?
# Difficulty Level: L2
arr = np.arange(9).reshape(3,3)
arr[::-1, :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [20]:
# 19. How to reverse the columns of a 2D array?
# Difficulty Level: L2
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [21]:
# 20. How to create a 2D array containing random floats between 5 and 10?
# Difficulty Level: L2

# sol1
sol1 = np.random.randint(5, 10, size=(5,3)) + np.random.random(size=(5,3))
print(sol1)
sol2 = np.random.uniform(low=5, high=10, size=(5,3))
print(sol2)
# hint
# random methods are really make people confused
# we can check the method using dir and list-comprehension
# and it just saved your time
# method_list = dir(np.random)
# [method for method in method_list
#                    if method.startswith('rand')]
# quick note
# random.ranint(low, high, size) --> [low, high) interger only
# random.random_integers(low, high, size) --> [low, high] interger only
# random.uniform(low, high, size) --> [low, high) float
# random.random(size) --> [0,1) float
# https://www.jianshu.com/p/214798dd8f93 簡書上的numpy.random相關函數整理，作者推薦

[[8.93855271 9.00077877 7.99221156]
 [9.61748151 9.61165316 6.00706631]
 [7.02306243 7.52477466 7.39986097]
 [9.04666566 8.97375552 7.23277134]
 [9.09060643 6.61838601 8.38246199]]
[[9.91615443 7.33381447 9.29970203]
 [8.40153769 7.25249626 5.06632481]
 [9.71100878 7.81644109 6.92708251]
 [5.07983126 6.15446913 6.20512733]
 [8.41631759 8.04998329 9.16597456]]


In [22]:
# 21. How to print only 3 decimal places in python numpy array?
# Difficulty Level: L1
rand_arr = np.random.random((5,3))
# sol1
np.round(rand_arr,3)
# sol2
np.set_printoptions(precision=3)
print(rand_arr)

# hint
# back_to_fefault option (by numpy documentation)
np.set_printoptions(edgeitems=3,infstr='inf',
linewidth=75, nanstr='nan', precision=8,
suppress=False, threshold=1000, formatter=None)

[[0.173 0.391 0.182]
 [0.755 0.425 0.208]
 [0.568 0.031 0.842]
 [0.45  0.395 0.927]
 [0.727 0.327 0.57 ]]


In [23]:
# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
# Difficulty Level: L1
rand_arr = np.random.random([3,3])/1e4
rand_arr
np.set_printoptions(suppress=True, precision=5)
rand_arr

# hint
# back_to_fefault option (by numpy documentation)
np.set_printoptions(edgeitems=3,infstr='inf',
linewidth=75, nanstr='nan', precision=8,
suppress=False, threshold=1000, formatter=None)

In [24]:
# 23. How to limit the number of items printed in output of numpy array?
# Difficulty Level: L1
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

# hint
# back_to_fefault option (by numpy documentation)
np.set_printoptions(edgeitems=3,infstr='inf',
linewidth=75, nanstr='nan', precision=8,
suppress=False, threshold=1000, formatter=None)

[ 0  1  2 ... 12 13 14]


In [25]:
# 24. How to print the full numpy array without truncating
# Difficulty Level: L1
a = np.arange(15)
np.set_printoptions(threshold=None)
print(a)

# hint
# back_to_fefault option (by numpy documentation)
np.set_printoptions(edgeitems=3,infstr='inf',
linewidth=75, nanstr='nan', precision=8,
suppress=False, threshold=1000, formatter=None)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
# 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
# Difficulty Level: L2
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [27]:
# 26. How to extract a particular column from 1D array of tuples?
# Difficulty Level: L2

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',',
                        names=['a','b','c','d','txt'],
                        dtype=None)
# More readable
# use names filed 
# documentation about named fields 
# https://docs.scipy.org/doc/numpy-1.15.0/user/basics.rec.html
iris_1d['txt'][:5]

C:\Users\yltsai\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:7: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  import sys


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S15')

In [28]:
# 27. How to convert a 1d array of tuples to a 2d numpy array?
# Difficulty Level: L2
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

# More readable
# Just use asarray to unpack the element
result = np.asarray(iris_1d)
result[:5]

C:\Users\yltsai\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, b'Iris-setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [29]:
# 28. How to compute the mean, median, standard deviation of a numpy array?
# Difficulty: L1

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris[:, 0:4] = iris[:, 0:4].astype(float)
print( 'mean ',iris[:, 0].mean())
print('median ', np.median(iris[:, 0]))
print('std ',iris[:, 0].std())

mean  5.843333333333335
median  5.8
std  0.8253012917851409


In [30]:
# 29. How to normalize an array so the values range exactly between 0 and 1?
# Difficulty: L2
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin) / (Smax - Smin)
S[:5]

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444])

In [31]:
# 30. How to compute the softmax score?
# Difficulty Level: L3

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
softmax_socre = np.exp(sepallength) / sum(np.exp(sepallength))
softmax_socre[:5]

# hint 
# softmax score --> 一種歸一化, 將原本的元素壓縮在0,1之間, 且所有元素和為1
# 這樣的歸一化能夠強調最大的值, 並使其他值遠小於最大值
# Wiki : https://zh.wikipedia.org/wiki/Softmax%E5%87%BD%E6%95%B0
print('The max of softmax score : ',softmax_socre.max(),
      'The mean of softmax score : ', softmax_socre.mean(), sep='\n')
# when to use?
# Logistic regression, NN, Maive Byes ....

The max of softmax score : 
0.036500296150864316
The mean of softmax score : 
0.0066666666666666645


In [32]:
# 31. How to find the percentile scores of a numpy array?
# Difficulty Level: L1
# Q. Find the 5th and 95th percentile of iris's sepallength


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print(np.quantile(sepallength, 0.05))
print(np.quantile(sepallength, 0.95))

4.6
7.254999999999998


In [33]:
# 32. How to insert values at random positions in an array?
# Difficulty Level: L2

# Q. Insert np.nan values at 20 random positions in iris_2d dataset

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

pos_x = np.random.randint(low=0, high=iris_2d.shape[0], size=20)
pos_y = np.random.randint(low=0, high=iris_2d.shape[1], size=20)
iris_2d[pos_x, pos_y] = np.nan
iris_2d[:10]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', nan, b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', nan, b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa']], dtype=object)

In [34]:
# 33. How to find the position of missing values in numpy array?
# Difficulty Level: L2
# Q. Find the number and position of missing values in iris_2d's sepallength (1st column)

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [35]:
# 34. How to filter a numpy array based on two or more conditions?
# Difficulty Level: L3

# Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition][:5]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ]])

In [36]:
# 35. How to drop rows that contain a missing value from a numpy array?
# Difficulty Level: L3:
# Q. Select the rows of iris_2d that does not have any nan value.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# mask or np.where
# np.isnan will flattern our 2d-array
# so followed will return shape = 600
# condintion = ~ np.isnan(iris_2d)
# iris_2d[condintion].shape

# then we do it by rowise
mask = [~ np.any(np.isnan(row)) for row in iris_2d]
print(iris_2d[mask].shape)
iris_2d[mask][:5]

(134, 4)


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [37]:
# 36. How to find the correlation between two columns of a numpy array?
# Difficulty Level: L2
# Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])

array([[1.        , 0.87175416],
       [0.87175416, 1.        ]])

In [38]:
# 37. How to find if a given array has any null values?
# Difficulty Level: L2
# iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

np.isnan(iris_2d).any()




True

In [39]:
# 38. How to replace all missing values with 0 in a numpy array?
# Difficulty Level: L2

# Q. Replace all ccurrences of nan with 0 in numpy array

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan


# More readable 
iris_2d = np.where(np.isnan(iris_2d), 0, iris_2d)
print(np.isnan(iris_2d).any())

False


In [40]:
# 39. How to find the count of unique values in a numpy array?
# Difficulty Level: L2

# Q. Find the unique values and the count of unique values in iris's species

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


np.unique(iris[:, -1], return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object), array([50, 50, 50], dtype=int64))

In [41]:
# 40. How to convert a numeric to a categorical (text) array?
# Difficulty Level: L2

# Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

# Less than 3 --> 'small'
# 3-5 --> 'medium'
# '>=5 --> 'large'

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Vectorlized

bins = np.array([0, 3, 5, 100])
def label_map(x):
    if x == 1:
        return 'small'
    elif x == 2:
        return 'medium'
    elif x == 3:
        return 'large'
    else:
        return np.nan
tmp = np.digitize(iris[:, 2].astype(float), bins)
v_label_map = np.vectorize(label_map)
v_label_map(tmp)[:5]

# Hint
# the comparision below when your data is really large
# use dictionary and list-comprehension


array(['small', 'small', 'small', 'small', 'small'], dtype='<U6')

In [42]:
# test_arr = np.random.randint(low=1, high=4, size=5000000)

%%time
label_map = {1 : 'small', 2 : 'medium', 3:'large'}
result = [label_map[element] for element in test_arr]
took 1.71s on my mac-air

In [43]:
# %%time
# def label_map(x):
#     if x == 1:
#         return 'small'
#     elif x == 2:
#         return 'medium'
#     elif x == 3:
#         return 'large'
#     else:
#         return np.nan
# v_label_map = np.vectorize(label_map)
# v_label_map(tmp)
# took 191 µs o my mac-air

# A brief report no stackoverflow
# https://stackoverflow.com/questions/35215161/most-efficient-way-to-map-function-over-numpy-array

In [44]:
# 41. How to create a new column from existing columns of a numpy array?
# Difficulty Level: L2

# Q. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
pi = np.pi

result = pi * iris_2d[:, 2].astype(float) * (iris_2d[:, 0].astype(float) ** 2) / 3
result[:5]

array([38.13265163, 35.20049849, 30.07237208, 33.23805027, 36.65191429])

In [45]:
# 42. How to do probabilistic sampling in numpy?
# Difficulty Level: L3
    
# Q. Randomly sample iris's species such that setose is twice the number of versicolor and virginica
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')


spcies_unq = np.unique(iris[:, -1])
p = [0.5, 0.25, 0.25]
result = np.random.choice(spcies_unq, size=100, p=p)
print('result array distribution :',np.unique(result, return_counts=True))

# hint
# you could see sampling documentation 
# https://docs.scipy.org/doc/numpy-1.16.0/reference/routines.random.html


result array distribution : (array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object), array([40, 34, 26], dtype=int64))


In [56]:
# 43. How to get the second largest value of an array when grouped by another array?
# Difficulty Level: L2

# Q. What is the value of second longest petallength of species setosa

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

condition = iris[:, -1] == b'Iris-setosa'

tmp = iris[condition, 2].astype(float)
np.unique(np.sort(tmp))[-2]

# hint
# numpy中並沒有像pd.Series一樣有ascending選項

1.7

In [65]:
# 44. How to sort a 2D array by a column
# Difficulty Level: L2

# Q. Sort the iris dataset based on sepallength column.


# More readable
# use name-filed
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
dtype=[('sepallength', '<f8'), ('sepalwidth', '<f8'),
       ('petallength', '<f8'), ('petalwidth', '<f8')
       ,('species', 'object')]

iris = np.genfromtxt(url, delimiter=',',names=names,
                    dtype = dtype)
np.sort(iris, order=['sepallength'])[:5]

array([(4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.4, 3. , 1.3, 0.2, b'Iris-setosa'),
       (4.4, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.5, 2.3, 1.3, 0.3, b'Iris-setosa')],
      dtype=[('sepallength', '<f8'), ('sepalwidth', '<f8'), ('petallength', '<f8'), ('petalwidth', '<f8'), ('species', 'O')])

In [67]:
# 45. How to find the most frequent value in a numpy array?
# Difficulty Level: L1

# Q. Find the most frequent value of petal length (3rd column) in iris dataset.

# More readable
# name field
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
dtype=[('sepallength', '<f8'), ('sepalwidth', '<f8'),
       ('petallength', '<f8'), ('petalwidth', '<f8')
       ,('species', 'object')]

iris = np.genfromtxt(url, delimiter=',',names=names,
                    dtype = dtype)

vals_arr, counts_arr = np.unique(iris['petallength'], return_counts=True)

vals_arr[np.argmax(counts_arr)]

# Hint
# 函數回傳結果為turple時，
# 用兩個變數接收結果

1.5

In [70]:
# 46. How to find the position of the first occurrence of a value greater than a given value?
# Difficulty Level: L2

# Q. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

# More readable
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
dtype=[('sepallength', '<f8'), ('sepalwidth', '<f8'),
       ('petallength', '<f8'), ('petalwidth', '<f8')
       ,('species', 'object')]

iris = np.genfromtxt(url, delimiter=',',names=names,
                    dtype = dtype)

np.argwhere(iris['petalwidth'] > 1.0)[0]

array([50], dtype=int64)

In [81]:
# 47. How to replace all values greater than a given value to a given cutoff?
# Difficulty Level: L2

# Q. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

np.random.seed(100)
a = np.random.uniform(1,50, 20)

# 巢狀np.where
# 若 a > 30, 則換成30, 若 < 30, 執行另一函式
# 另一函式 : a < 10, 換成 10, 否, 為原本值
# 用途廣泛
np.where( a > 30, 
              30, 
          np.where(a < 10,
                       10,
                       a))
# clip
# when to use
# 純數字，取中間時
np.clip(a, a_min=10, a_max=30)[:5]

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ])

In [83]:
# 48. How to get the positions of top n values from a numpy array?
# Difficulty Level: L2

# Q. Get the positions of top 5 maximum values in a given array a.

np.random.seed(100)
a = np.random.uniform(1,50, 20)

np.argsort(a)[-5:]

# Hint
# 條件 : 找值
# np.where 返回整個array的值
# np.argwhere 返回index
# 排序
# np.sort 值排序
# np.argsort 值排序，返回index
# When to use
# Eg. 返回特徵重要度最大的index, 用於取出特徵欄位

array([18,  7,  3, 10, 15], dtype=int64)