* aa

In [1]:
import numpy as np
np.random.seed(seed=42)

In [2]:
# 13. How to get the positions where elements of two arrays match?
# Difficulty Level: L2
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.argwhere(a==b).reshape(-1)

array([1, 3, 5, 7], dtype=int64)

In [3]:
# 14. How to extract all numbers between a given range from a numpy array?
# Difficulty Level: L2
a = np.array([2, 6, 1, 9, 10, 3, 27])

idx = np.argwhere((5 <= a) & (a<=10)).reshape(-1)
a[idx]

array([ 6,  9, 10])

In [4]:
# 15. How to make a python function that handles scalars to work on numpy arrays?
# Difficulty Level: L2
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
v_maxx = np.vectorize(maxx, otypes=[int])

# when to use
# you want faster speed but no np function suit your case
# then define it, vectorlize it
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
v_maxx(a, b)

array([6, 7, 9, 8, 9, 7, 5])

In [5]:
# 16. How to swap two columns in a 2d numpy array?
# Difficulty Level: L2
arr = np.arange(9).reshape(3,3)
# when to use
# change your feature values if they are numpy.array
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [6]:
# 17. How to swap two rows in a 2d numpy array?
# Difficulty Level: L2
arr = np.arange(9).reshape(3,3)
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [7]:
# 18. How to reverse the rows of a 2D array?
# Difficulty Level: L2
arr = np.arange(9).reshape(3,3)
arr[::-1, :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [8]:
# 19. How to reverse the columns of a 2D array?
# Difficulty Level: L2
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [12]:
# 20. How to create a 2D array containing random floats between 5 and 10?
# Difficulty Level: L2

# sol1
sol1 = np.random.randint(5, 10, size=(5,3)) + np.random.random(size=(5,3))
print(sol1)
sol2 = np.random.uniform(low=5, high=10, size=(5,3))
print(sol2)
# hits
# random methods are really make people confused
# we can check the method using dir and list-comprehension
# and it just saved your time
# method_list = dir(np.random)
# [method for method in method_list
#                    if method.startswith('rand')]
# quick note
# random.ranint(lower, upper, size) --> [lower, upper) interger only
# random.random_integers(lower, upper, size) --> [lower, upper] interger only
# random.uniform(lower, upper, size) --> [lower, upper) float
# random.random(size) --> [0,1) float

[[6.69478493 8.88046784 9.62435405]
 [7.29563369 5.10549426 8.45653457]
 [9.21844044 8.41650995 9.88328026]
 [9.32434502 7.12208795 9.35629784]
 [8.90682844 9.27213225 7.64769012]]
[[5.00260188 6.76284428 6.52390629]
 [5.82327927 7.6704471  7.42414986]
 [8.46218016 6.34706167 6.22062761]
 [5.84145521 6.0938211  7.79051001]
 [7.01918086 5.32446124 6.26957707]]


In [22]:
# 21. How to print only 3 decimal places in python numpy array?
# Difficulty Level: L1
rand_arr = np.random.random((5,3))
# sol1
np.round(rand_arr,3)
# sol2
np.set_printoptions(precision=3)
print(rand_arr)

# hint
# back_to_fefault option (by numpy documentation)
np.set_printoptions(edgeitems=3,infstr='inf',
linewidth=75, nanstr='nan', precision=8,
suppress=False, threshold=1000, formatter=None)

[[0.995 0.47  0.28 ]
 [0.883 0.748 0.953]
 [0.331 0.553 0.572]
 [0.98  0.075 0.306]
 [0.191 0.268 0.485]]


In [21]:
# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
# Difficulty Level: L1
rand_arr = np.random.random([3,3])/1e4
rand_arr
np.set_printoptions(suppress=True, precision=5)
rand_arr

# hint
# back_to_fefault option (by numpy documentation)
np.set_printoptions(edgeitems=3,infstr='inf',
linewidth=75, nanstr='nan', precision=8,
suppress=False, threshold=1000, formatter=None)

In [25]:
# 23. How to limit the number of items printed in output of numpy array?
# Difficulty Level: L1
a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)

# hint
# back_to_fefault option (by numpy documentation)
np.set_printoptions(edgeitems=3,infstr='inf',
linewidth=75, nanstr='nan', precision=8,
suppress=False, threshold=1000, formatter=None)

[ 0  1  2 ... 12 13 14]


In [28]:
# 24. How to print the full numpy array without truncating
# Difficulty Level: L1
a = np.arange(15)
np.set_printoptions(threshold=None)
print(a)

# hint
# back_to_fefault option (by numpy documentation)
np.set_printoptions(edgeitems=3,infstr='inf',
linewidth=75, nanstr='nan', precision=8,
suppress=False, threshold=1000, formatter=None)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [30]:
# 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
# Difficulty Level: L2
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)